tap "homebrew/bundle"
tap "homebrew/cask"

brew "bash"
brew "ag"
brew "curl"
brew "direnv"
brew "fzf"
brew "jq"
brew "neovim"
brew "shellcheck"
brew "tmux"
brew "tree"

cask '1password'
cask '1password-cli'
cask 'anki'
cask 'docker'
cask 'firefox'
cask 'google-backup-and-sync'
cask 'kitty'
cask 'notion'
cask 'shiftit'
cask 'spotify'
