tap "homebrew/bundle"
tap "homebrew/cask"
tap "cloudfoundry/tap"

brew "ag"
brew "neovim"
brew "curl"
brew "direnv"
brew "jq"
brew "tree"
brew "tmux"
brew "fzf"
brew "shellcheck"
brew "cloudfoundry/tap/cf-cli"

cask 'kitty'
cask 'notion'
cask 'firefox'
cask 'shiftit'
cask '1password'
cask '1password-cli'

