matches:

  - trigger: ":email"
    replace: mbrauer@vmware.com

  - trigger: ":team"
    replace: sawalther@vmware.com,cquates@vmware.com,ddubson@vmware.com,dgarnier@vmware.com,ikhaimovich@vmware.com,fhanik@vmware.com

  - trigger: ":cn"
    replace: constellation

  - trigger: ":pkg"
    replace: $|$.tanzu.vmware.com

  - trigger: ":cm"
    replace: cert-manager.tanzu.vmware.com

  - trigger: ":tcm"
    replace: cert-manager.community.tanzu.vmware.com

  - trigger: ":sso"
    replace: sso.apps.tanzu.vmware.com

  - trigger: ":domain"
    replace: identity.team

  - trigger: ":local"
    replace: localhost.identity.team

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":ccs"
    replace: "**[suggestion, ]:** "
      
  - trigger: ":cci"
    replace: "**[issue, ]:** "

  - trigger: ":cct"
    replace: "**[thought]:** "

  - trigger: ":ccq"
    replace: "**[question, ]:** "

  - trigger: ":ccp"
    replace: "**[praise]:** "

  - trigger: ":todo"
    replace: "**[todo]** "

  - trigger: ":as"
    replace: "AuthServer"

  - trigger: ":cr"
    replace: "ClientRegistration"
      
  - trigger: ":wr"
    replace: "WorkloadRegistration"
      
  - trigger: ":cutl"
    replace: "ClusterUnsafeTestLogin"
      
  - trigger: ":cwrc"
    replace: "ClusterWorkloadRegistrationClass"
      
